### ISSUE TITLE
Windows bug report

### ISSUE THREAD

**Issue by danrobi11** [pinnaculum/galacteek#30]
v0.4.39
Wont let me generate random username.
And this is what I get when I manually add a username.
Tested with win7 in vb

[ 06:55:51] galacteek.application: IPFS daemon started
[ 06:55:52] galacteek.application: IPFS daemon is ready
[ 06:56:34] galacteek.hashmarks: Synchronizing hashmarks database ...
[ 06:56:34] galacteek.hashmarks: Synchronizing: PyModule source: core
[ 06:56:34] galacteek.hashmarks: Synchronizing: GIT source: None (https://github.com/galacteek/hashmarks-dwebland)
[ 06:56:40] galacteek.core.profile: profile (default): Generating main IPNS key
[ 06:56:41] galacteek.core.profile: profile (default): Creating RSA keypair
[ 06:56:44] galacteek.core.profile: profile (default): Successfully created RSA keypair
[ 06:56:44] galacteek.core.profile: profile (default): Registering keys
[ 06:56:44] galacteek.core.ctx: Could not initialize profile: [Errno 2] No such file or directory: 'C:\\Users\\m\\AppData\\Local\\Temp\\_MEI15162\\random_username\\data\\adjectives.txt'
Traceback (most recent call last):
  File "galacteek\core\ctx.py", line 1121, in profileNew
  File "galacteek\core\profile.py", line 777, in init
  File "galacteek\ipfs\wrappers.py", line 69, in wrapper
  File "galacteek\ipfs\wrappers.py", line 42, in _operation
  File "galacteek\core\profile.py", line 874, in cryptoInit
  File "galacteek\ipfs\wrappers.py", line 69, in wrapper
  File "galacteek\ipfs\wrappers.py", line 42, in _operation
  File "galacteek\core\profile.py", line 916, in cryptoRegisterKeys
  File "galacteek\core\profile.py", line 940, in setupProfileEDag
  File "galacteek\core\profile.py", line 920, in randomUsername
  File "random_username\generate.py", line 8, in generate_username
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\m\\AppData\\Local\\Temp\\_MEI15162\\random_username\\data\\adjectives.txt'
[ 06:57:04] galacteek.core.profile: profile (default): Registering keys
[ 06:57:04] galacteek.core.ctx: Could not initialize profile: [Errno 2] No such file or directory: 'C:\\Users\\m\\AppData\\Local\\Temp\\_MEI15162\\random_username\\data\\adjectives.txt'
Traceback (most recent call last):
  File "galacteek\core\ctx.py", line 1121, in profileNew
  File "galacteek\core\profile.py", line 777, in init
  File "galacteek\ipfs\wrappers.py", line 69, in wrapper
  File "galacteek\ipfs\wrappers.py", line 42, in _operation
  File "galacteek\core\profile.py", line 874, in cryptoInit
  File "galacteek\ipfs\wrappers.py", line 69, in wrapper
  File "galacteek\ipfs\wrappers.py", line 42, in _operation
  File "galacteek\core\profile.py", line 916, in cryptoRegisterKeys
  File "galacteek\core\profile.py", line 940, in setupProfileEDag
  File "galacteek\core\profile.py", line 920, in randomUsername
  File "random_username\generate.py", line 8, in generate_username
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\m\\AppData\\Local\\Temp\\_MEI15162\\random_username\\data\\adjectives.txt'

**Comment by danrobi11** [comment]
Ok working now with Galacteek-19fb3d11.exe
Good job!
